name: Rust-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
#asd

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  generate-sbom:
    name: Generate SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # TODO 3: installer cargo-cyclonedx
      # https://github.com/CycloneDX/cyclonedx-rust-cargo
      # - name: Install cargo-cyclonedx
      #   run: 
      # TODO 4: generer le SBOM
      # https://github.com/CycloneDX/cyclonedx-rust-cargo/blob/main/cargo-cyclonedx/README.md
      # - name: Generate SBOM
      #   run: 
      # TODO 5: donner le bon nom pour l'artefact
      # https://github.com/CycloneDX/cyclonedx-rust-cargo/blob/main/cargo-cyclonedx/README.md
      # https://github.com/actions/upload-artifact#usage
      # - name: Upload SBOM as artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: sbom
      #     path: 
